### ISSUE TITLE
are you even serious about this?

### ISSUE THREAD

**Issue by terrorizers** [okxapi/python-okx#11]
https://github.com/okxapi/python-okx/blob/709947bce423491cc470130c151308b3766ed629/example/get_started_en.ipynb
AttributeError: module 'okx.MarketData' has no attribute 'MarketAPI'

seems like a joke, i cant even believe only 14 ppl have starred this, obviously is so badly maintained nobody actually use it lol

**Comment by okxapi** [comment]
Currently, the method name style for the endpoint has been adjusted.

-------
import okx.market as MarketData
if __name__ == '__main__':
   flag = "0"  # real trading:0 , demo trading：1
   marketDataAPI = MarketData.Market(flag=flag)
   result = marketDataAPI.get_tickers(
      instType="SPOT"
   )
   print(result)

----


Maybe some of the content has not been adjusted accordingly. Will check that in our doc. Thanks for your reminder.

**Comment by okxapi** [comment]
Fixed the issue in version 0.1.6, thanks for your reminder.

**Comment by okxapi** [comment]
we're very sorry,this issues had been resolved.pls upgrade python-okx version.
