### ISSUE TITLE
whitelist address function

### ISSUE THREAD

**Issue by ajesuscode** [okxapi/python-okx#12]
Hello
When trying to implement a withdrawl method, I do get response with  { address is not whitelisted} is there any method or other solution how to get address whitelisted or perform withdrawl without whitelisting the address?

**Comment by okxapi** [comment]
The withdrawal address must be labeled `trusted`.
[image]
You can authorize the address by website.
[image]

**Comment by ajesuscode** [comment]
I assume there is no other way around? So each new address I want to  withdrawal a funds needs to be trusted ? Would be nice to have an api version of verification))) Thanks

**Comment by okxapi** [comment]
No API version of verification for safety concerns, I guess.
