### ISSUE TITLE
Unable to subscribe ws channels

### ISSUE THREAD

**Issue by mahdimm1** [okxapi/python-okx#15]
Hi! I tried to run the test script for the public websocket in [test/WsPublicTest.py](https://github.com/okxapi/python-okx/blob/master/test/WsPublicTest.py). But it's unable to subscribe to the channels and kept on returning this ConnectionDone error:
`WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.],retried 1 times
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.],retried 1 times
'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.],retried 4 times
...`
i'm using python 3.10.6 and python-okx 0.1.8

**Comment by okxapi** [comment]
You may check your network locally, such as the VPN setting.

**Comment by mahdimm1** [comment]
I tested the code on the cloud servers and got the same error.
The problem is not related to the internet connection!
