### ISSUE TITLE
websocket不能用

### ISSUE THREAD

**Issue by creater-xuwei** [okxapi/python-okx#17]
websocket订阅报错：
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

**Comment by okxapi** [comment]
Is this still an issue?

**Comment by CryptoTraderJason** [comment]
> Is this still an issue?

yes, on first run, I got this error:

`ModuleNotFoundError: No module named 'autobahn' `

so I installed autobahn.

on second run, I got this error:

`UserWarning: You do not have a working installation of the service_identity
module: 'No module named service_identity`

I then installed service_identity

on third run, I got this error:

`loginSocket callback: {'event': 'error', 'msg': 'Invalid sign', 'code': '60007'}
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 1 times
loginSocket callback: {'event': 'error', 'msg': 'Invalid sign', 'code': '60007'}
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.`

This is really surprising me, thank you for your work on this python wrapper, but have you ever tried it yourself before releasing it? Please fix it if you can. Thank you.

**Comment by Micro-Rice** [comment]
I also got the error :
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 1 times

**Comment by Pborz** [comment]
Hello everyone,

After my back-and-forth with the issues in the foundational libraries Autobahn and Twisted, I've made progress and narrowed down the problem.  hope I can collaborate to work on this together.

```
    def subscribeSocket(self, args: list, callback):
        channelArgs = {}
        channelParamMap = {}
        WsUtils.checkSocketParams(args, channelArgs, channelParamMap)
        if len(channelArgs) < 1:
            return False
        for channel in channelArgs:
            subSet = channelParamMap.get(channel, set())
            if self.isPrivate:
                privateKey = self.getPrivateKey(channel)
                if privateKey not in self.factories:
                    reactor.callFromThread(self.loginSocket, channel)
                    time.sleep(2)
                    newFactory = self.initSubscribeFactory(args=channelArgs[channel], subSet=subSet, callback=callback)
                    reactor.callFromThread(self.resetConnection, newFactory, channel)
                    continue
            factory = self.initSubscribeFactory(args=channelArgs[channel], subSet=subSet, callback=callback)
            self.factories[channel] = factory
            reactor.callFromThread(self.addConnection, channel)

    def addConnection(self, channel):
        self.conns[channel] = connectWS(self.factories[channel])
```

Firstly, in this context, the connectWS function has some issues. It's using Twisted's reactor to call connectSSL. Strangely, I stumbled upon the fact that while connectSSL can connect to Okex, it can't connect to Okx. So, I reached out to relevant people in the Twisted community and they mentioned a major overhaul using the endpoint approach. I gave it a rough try, but I'm not entirely confident, and I've also inquired whether it's possible to stick closer to the IConnector class, but there's no response yet.
Here's the link to the issue for reference: [twisted/twisted#11928](https://github.com/twisted/twisted/issues/11928))

**Comment by Pborz** [comment]
#25 
(Here's the link to the issue for reference: [twisted/twisted#11928](https://github.com/twisted/twisted/issues/11928))

@Micro-Rice @CryptoTraderJason @creater-xuwei

**Comment by okxapi** [comment]
hi, guys, you may refer to the new websocket example
大家可以参考下最新的websocket例子
https://github.com/okxapi/python-okx/blob/master/test/WsPrivateAsyncTest.py
https://github.com/okxapi/python-okx/blob/master/test/WsPublicAsyncTest.py
