### ISSUE TITLE
Missing stop loss and take profit in Trade API

### ISSUE THREAD

**Issue by samueledelloca** [okxapi/python-okx#18]
Referring to the [official OKX REST API Documentation](https://www.okx.com/docs-v5/en/#rest-api-trade-place-order) specifically to the "Place order" request, I see that many optional parameter are missing in the Python wrapper method (`Trade.TradeAPI.place_order`).

I'm developing a bot which is already working on Bybit exchange, I would like to integrate it also with OKX. For doing that I need the possibility to set stop loss and take profit when placing an order, so the parameter that are missing in the Python method are `tpTriggerPx`, `tpOrdPx`, `tpTriggerPxType`, `slTriggerPx`, `slOrdPx` and `slTriggerPxType`.

I am using what should currently be the latest version, 0.1.9. I really appreciate your work and look forward to this feature!

**Comment by okxapi** [comment]
hi! we will add these soon!
