### ISSUE TITLE
Trade API missing tag, clOrdId params for closing orders

### ISSUE THREAD

**Issue by jssuk1** [okxapi/python-okx#19]
Trade API missing tag, clOrdId params are missing for closing orders which leads to a loss in commission calculations.  However, opening order has those params.

PROBLEM:
Close Positions
    def close_positions(self, instId, mgnMode, posSide='', ccy='',autoCxl=''):
        params = {'instId': instId, 'mgnMode': mgnMode, 'posSide': posSide, 'ccy': ccy,'autoCxl':autoCxl}
        return self._request_with_params(POST, CLOSE_POSITION, params)
        
        

while opening orders are ok and you can see that tag and clOrdId are present. Please update

place_order(self, instId, tdMode, side, ordType, sz, ccy='', **clOrdId='',** **tag=''**, posSide='', px='',
                    reduceOnly='', tgtCcy=''):
        params = {'instId': instId, 'tdMode': tdMode, 'side': side, 'ordType': ordType, 'sz': sz, 'ccy': ccy,
                  'clOrdId': clOrdId, 'tag': tag, 'posSide': posSide, 'px': px, 'reduceOnly': reduceOnly,
                  'tgtCcy': tgtCcy}

**Comment by okxapi** [comment]
coming up soon. thanks
