### ISSUE TITLE
Trade api doesn't work.

### ISSUE THREAD

**Issue by Hearty07** [okxapi/python-okx#2]
{"code":"50004","data":[],"msg":"API endpoint request timeout "}, 400
![image](https://user-images.githubusercontent.com/37877173/225244973-d1378582-ee86-417d-a40c-05da0bad9575.png)

**Comment by Hearty07** [comment]
the REST API services are not available now ...
{
  "code": "50001",
  "data": [],
  "msg": "服务暂时不可用，请稍后重试"
}

**Comment by okxapi** [comment]
The demo trading is under maintenance. You may try later.

**Comment by Hearty07** [comment]
Now the problem is solved
