### ISSUE TITLE
Error while try to subscribe to chanel tickers

### ISSUE THREAD

**Issue by Purik** [okxapi/python-okx#21]
1. According to https://www.okx.com/docs-v5/en/#overview I use URL: wss://ws.okx.com:8443/ws/v5/public as public websocket API endpoint
2. I connect to this URL, successfully
3. According to manual https://www.okx.com/docs-v5/en/#websocket-api-subscribe I try to send to websocket data 
"{
  "op": "subscribe",
  "args": [
    {
      "channel": "tickers",
      "instId": "LTC-USD"
    }
  ]
}"

5. I see response with Error: "{"event":"error","msg":"channel:tickers,instId:LTC-USD doesn't exist","code":"60018"}"

**What is wrong? I repeat steps from official guide**

**Comment by okxapi** [comment]
Hi, LTC-USD is not an available instruments on OKX. Try LTC-USDT.
See all available spot instruments https://www.okx.com/api/v5/public/instruments?instType=SPOT
