### ISSUE TITLE
对于此SDK原生不支持代理及和clash for windows开启全局代理报错问题的解决方案

### ISSUE THREAD

**Issue by Willdiedog** [okxapi/python-okx#24]
由于众所周知的原因，国内不能直接访问okx服务器，必须使用魔法工具，但这个库并不支持设置代理服务器，在本人尝试后得出以下解决方案，当然，这仅仅是为了方便开发和调试，生产环境需要考虑延迟和稳定性等因素建议直接使用国外VPS。
**方案1：**
直接开启clash for windows的TUN mode
**方案2：**
使用monkeypatch对本库底层进行修改，此法需要安装httpx的socks代理支持库 `pip install httpx[socks]`
代码如下
```python
PROXY_HOST='localhost'
PROXY_PORT=7890
#为底层httpx库强行设置代理
os.environ['HTTP_PROXY']='socks5://{}:{}'.format(PROXY_HOST, PROXY_PORT)
os.environ['HTTPS_PROXY']='socks5://{}:{}'.format(PROXY_HOST,PROXY_PORT)
#打个猴子补丁强行为WebSocket设置代理
from okx.websocket.WsConnectManager import WsConnectManager

old_addConnection=WsConnectManager.addConnection

def ProxyMonkeyPatch(self, channel):
    self.factories[channel].proxy={'host':PROXY_HOST,'port':PROXY_PORT}
    old_addConnection(self, channel)

WsConnectManager.addConnection=ProxyMonkeyPatch
```

**Comment by cvtutorials** [comment]
如何借助国外VPS实现呢

**Comment by cvtutorials** [comment]
使用TUN mode会对其他正常操作产生影响

**Comment by tafse** [comment]
还是报ssl错误，加不加代理结果一样。
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 1 times

**Comment by Hotege** [comment]
各个WebAPI模块的构造函数倒是有个proxy参数，可以传入代理的地址，不知道是不是这个issue之后加的feature

**Comment by okxapi** [comment]
可以考虑采用新的异步方式实现
https://github.com/okxapi/python-okx/blob/master/test/WsPrivateAsyncTest.py
https://github.com/okxapi/python-okx/blob/master/test/WsPublicAsyncTest.py
