### ISSUE TITLE
TP/SL not showing when using  tradeAPI.get_order_list()

### ISSUE THREAD

**Issue by jcabourne** [okxapi/python-okx#27]
Hi,

Does anyone know how to amend the TP and SL with the api. When i request my order lists i am not getting any of the TP or SL orders. Without them being listed i am unable to get the orderIDs to amend the orders. I also cant see a way to amend a positions with an equivalent tradeAPI.amend_position().

Any help would be really appreciated

**Comment by Pborz** [comment]
hello, do you once connect and run the application got error ?: 

WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 1 times
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 2 times

is your wss `okx.com` or `okex.com` ?  THX

**Comment by BigXia** [comment]
When i request my order lists i am not getting any of the TP or SL orders.
