### ISSUE TITLE
APIKey does not match current environment

### ISSUE THREAD

**Issue by tracyzhou77** [okxapi/python-okx#30]
调用 AccountAPI  get_account_balance 
报错：APIKey does not match current environment
用之前版本的 sdk 是可以正常运行的，不知道这是什么原因

**Comment by okxapi** [comment]
可以检查apikey和环境是否匹配

**Comment by TzujuiWang** [comment]
Most likely you are placing order in the demo environment.
Change your code：
flag = "0"  # Production trading: 0, Demo trading: 1

**Comment by openhe-hub** [comment]
应该是模拟环境和实盘环境的区别，请求头添加：headers["x-simulated-trading"] = "1" 为模拟盘
