### ISSUE TITLE
websocket无法使用代理连接

### ISSUE THREAD

**Issue by 17654567443224** [okxapi/python-okx#36]
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 2 times

**Comment by avorobiev** [comment]
Try to use
"wss://wspap.okex.com:8443/ws/v5/public" 
instead of 
"wss://wspap.okx.com:8443/ws/v5/public".
For more information look at closed issue https://github.com/okxapi/python-okx/issues/17 and linked with it https://github.com/twisted/twisted/issues/11928

**Comment by okxapi** [comment]
You may refer to this new example
https://github.com/okxapi/python-okx/blob/master/test/WsPublicAsyncTest.py
