### ISSUE TITLE
获取历史数据时的before和after参数应该是什么格式？

### ISSUE THREAD

**Issue by kjdsfbchkadwbcuiwbcfiw** [okxapi/python-okx#38]
`marketDataAPI.get_history_candlesticks(instId =symbol,after = after,before = before,bar='1Dutc',limit=100)`
我使用这个函数获取某一个标的的日线数据，after和before按照官方文档都设置为l毫秒的Unix 时间戳，但提取的数据始终为空
时间戳的代码如下：
`date_obj = datetime.strptime(date, "%Y-%m-%d")
    after = int(date_obj.timestamp()*1000)`
请问应该如何呢？谢谢

**Comment by okxapi** [comment]
after的时间是一个离现在更近的时间，before的时间是一个离现在更远的时间
`import okx.MarketData as MarketData
from datetime import datetime

flag = "0"  # 实盘:0 , 模拟盘：1

marketDataAPI = MarketData.MarketAPI(flag=flag)

# 获取交易产品历史K线数据
date = "2023-12-07"
date_obj = datetime.strptime(date, "%Y-%m-%d")
afterTs = int(date_obj.timestamp()*1000)

date = "2023-12-01"
date_obj = datetime.strptime(date, "%Y-%m-%d")
beforeTs = int(date_obj.timestamp()*1000)

result = marketDataAPI.get_history_candlesticks(
    instId="BTC-USDT",
    after = afterTs,
    before = beforeTs
)
print(result)`
