### ISSUE TITLE
pip install python-okx --upgrade 报错

### ISSUE THREAD

**Issue by tonytao0** [okxapi/python-okx#45]
![image](https://github.com/okxapi/python-okx/assets/57481654/a83eddec-26e8-43e3-8a7b-aaaf70a0f853)

**Comment by tonytao0** [comment]
手动下载：https://pypi.org/project/python-okx/#files
修改setup.py文件后解决: 
![image](https://github.com/okxapi/python-okx/assets/57481654/1438f290-2590-4d55-b3a1-45732b01ecb8)

执行：
python setup.py build
python setup.py install

**Comment by baby5** [comment]
> 手动下载：https://pypi.org/project/python-okx/#files 修改setup.py文件后解决: ![image](https://private-user-images.githubusercontent.com/57481654/293336389-1438f290-2590-4d55-b3a1-45732b01ecb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDg4NzYsIm5iZiI6MTcwNDQ0ODU3NiwicGF0aCI6Ii81NzQ4MTY1NC8yOTMzMzYzODktMTQzOGYyOTAtMjU5MC00ZDU1LWIzYTEtNDU3MzJiMDFlY2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5NTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzI0ZWFhZTY0ZDU3ZDA4MzZlOGVjYjM3OWJmY2E2YzJjNzgyMTE4NjMxOGI2YjFmMmIyNTY4MGY0NjNjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vxEx3UnGaDavGa-aWCf7PV67ivKIR5LC66QyrU0H6p4)
> 
> 执行： python setup.py build python setup.py install

可以直接执行 pip install .

**Comment by okxapi** [comment]
问题已修复，version：0.2.6
