### ISSUE TITLE
there is a spelling mistake in the project file 'WsPprivateAsync'

### ISSUE THREAD

**Issue by Pborz** [okxapi/python-okx#46]
actually it should be WsPrivateAsync

it is ok in the code:
class WsPrivateAsync:
    def __init__(self, apiKey, passphrase, secretKey, url, useServerTime):
        self.url = url
        self.subscriptions = set()
        self.callback = None
        self.loop = asyncio.get_event_loop()
        self.factory = WebSocketFactory(url)
        self.apiKey = apiKey
        self.passphrase = passphrase
        self.secretKey = secretKey
        self.useServerTime = useServerTime

but the py file is 'Ws**Pp**rivateAsync.py'

**Comment by Pborz** [comment]
and if my dear okxapi bro, you can fix new update for you project `okx sample market maker` then should be really really good !! but if you're busy I'll do it still, but not so smoothly then. THX

**Comment by okxapi** [comment]
fixed
