### ISSUE TITLE
client.py中的获取系统时间json解析是不是有问题？

### ISSUE THREAD

**Issue by Hearty07** [okxapi/python-okx#47]
def _get_timestamp(self):
        request_path = c.API_URL + c.SERVER_TIMESTAMP_URL
        response = self.client.get(request_path)
        if response.status_code == 200:
            **return response.json()['ts']**
        else:
            return ""

![image](https://github.com/okxapi/python-okx/assets/37877173/0bd3a517-37d1-4010-93a1-05f79b57a5e4)

看起来应该是:
return response.json()['data'][0]['ts']

并且为什么use_server_time为True，会出现Timestamp request expired错误呢？

**Comment by okxapi** [comment]
issue solved
