### ISSUE TITLE
请教能用API实现涨幅榜吗？

### ISSUE THREAD

**Issue by ydqsbfsyi** [okxapi/python-okx#48]
app内的涨幅榜，不完善，只能用“今日涨跌”排序，来挑选涨幅前列的品种。

想实现：用15分钟涨幅，来排序（遍历所有的永续品种）。

不知道用API，有没有可能实现？

**Comment by okxapi** [comment]
行情的基础数据可以拿到，这种分析数据肯定是可以实现的
