### ISSUE TITLE
How to add Stop Loss?

### ISSUE THREAD

**Issue by Arex360** [okxapi/python-okx#49]
i am doing future trading, but i don't know how can i place stop loss?
`symbol = "ADA"`
`result = tradeAPI.place_order(
        instId=f"{symbol}-USDT-SWAP",
        tdMode="isolated",
        side="buy",
        posSide="short",
        ordType="market",
        px="10",
        sz="100"
        )`

**Comment by Pavel14701** [comment]
# Take profit, long
result = tradeAPI.place_algo_order(
    instId=f"{ticker}-USDT-SWAP",
    tdMode="cross",
    side="sell",
    posSide="long",
    ordType="conditional",
    sz=size,
    tpTriggerPx=tpPrice,
    tpOrdPx="-1",
    tpTriggerPxType="last"
    )


# Stop loss, long
result = tradeAPI.place_algo_order(
    instId=f"{ticker}-USDT-SWAP",
    tdMode="cross",
    side="sell",
    posSide="long",
    ordType="conditional",
    sz=size,
    slTriggerPx=tpPrice,
    slOrdPx="-1",
    slTriggerPxType="last"
    )
