### ISSUE TITLE
please explain the detail of subAccount module

### ISSUE THREAD

**Issue by www5226448** [okxapi/python-okx#50]
1.how to use the set_permission_transfer_out and subAccount_transfer functions？
2.how to retrieve the deposit addresses of subaccount？

thanks

**Comment by www5226448** [comment]
let‘s be more specific，
what if i want transfer usdc from main account to sub account 'sub1', how to construct the parameters?

```
subAccount_transfer(ccy='USDC',amt='1',froms='18',to='18',
                         fromSubAccount='?????',toSubAccount='sub1')
```

**Comment by caronwang** [comment]
subAccount_transfer means to make funding transfer between subaccounts. If you want to transfer from main account to sub account ,you should refer to API : https://www.okx.com/docs-v5/en/?python#funding-account-rest-api-funds-transfer

import okx.Funding as Funding

# API initialization
apikey = "YOUR_API_KEY"
secretkey = "YOUR_SECRET_KEY"
passphrase = "YOUR_PASSPHRASE"

flag = "0"  # Production trading: 0, Demo trading: 1

fundingAPI = Funding.FundingAPI(apikey, secretkey, passphrase, False, flag)

# Funds transfer
result = fundingAPI.funds_transfer(
    type="1",
    ccy="USDT",
    amt="1",
    from_="6",
    to="18",
    subAcct="sub1"
)
print(result)

**Comment by caronwang** [comment]
1. how to use the set_permission_transfer_out and subAccount_transfer functions？
You may refer to OKX online doc to get details:
https://www.okx.com/docs-v5/en/#sub-account-rest-api-set-permission-of-transfer-out

```
import okx.SubAccount as SubAccount

# API initialization
apikey = "YOUR_API_KEY"
secretkey = "YOUR_SECRET_KEY"
passphrase = "YOUR_PASSPHRASE"

flag = "1"  # Production trading: 0, Demo trading: 1

subAccountAPI = SubAccount.SubAccountAPI(apikey, secretkey, passphrase, False, flag)

# Set permission of transfer out for sub-account
result = subAccountAPI.set_permission_transfer_out(
    subAcct="hahawang1",
    canTransOut=False
)
print(result)
```

2. how to retrieve the deposit addresses of subaccount
user the sub-account APIKey to call API: https://www.okx.com/docs-v5/en/?python#funding-account-rest-api-get-deposit-address

```
import okx.Funding as Funding

# API initialization
apikey = "YOUR_API_KEY"
secretkey = "YOUR_SECRET_KEY"
passphrase = "YOUR_PASSPHRASE"

flag = "0"  # Production trading: 0, Demo trading: 1

fundingAPI = Funding.FundingAPI(apikey, secretkey, passphrase, False, flag)

# Get deposit address
result = fundingAPI.get_deposit_address(
    ccy="USDT"
)
print(result)
```
