### ISSUE TITLE
get_account_bills_archive can we add begin and end so we can find info within a specified timeframe?

### ISSUE THREAD

**Issue by Hoodie2389** [okxapi/python-okx#58]
# Get Bills Details (recent 3 months)
    def get_account_bills_archive(self, instType='', ccy='', mgnMode='', ctType='', type='', subType='', after='', before='',
                          limit=''):
        params = {'instType': instType, 'ccy': ccy, 'mgnMode': mgnMode, 'ctType': ctType, 'type': type,
                  'subType': subType, 'after': after, 'before': before, 'limit': limit}
        return self._request_with_params(GET, BILLS_ARCHIVE, params)

https://www.okx.com/docs-v5/en/?python#trading-account-rest-api-get-bills-details-last-3-months
in this docs begin and end we can utilize so be great if we can add these 2 into the params

**Comment by okxapi** [comment]
Please update to the latest version and have a try.
