### ISSUE TITLE
module 'okx.consts' has no attribute 'API_URL'

### ISSUE THREAD

**Issue by Hearty07** [okxapi/python-okx#6]
in _request
    timestamp = self._get_timestamp()
  File "C:\Users\Hearty\AppData\Local\Programs\Python\Python310\lib\site-packages\okx\client.py", line 52, in _get_timestamp
    request_path = c.API_URL + c.SERVER_TIMESTAMP_URL
AttributeError: module 'okx.consts' has no attribute 'API_URL'

使用use_server_time=True以后出现上述问题，另外是否使用server_time区别是什么？

**Comment by Hearty07** [comment]
[Repair submission]:
https://github.com/Hearty07/python-okx/commit/7f9a76d9a624f81c4776b447ca36579fbb723bb9

**Comment by okxapi** [comment]
this issues had been resolved.pls upgrade python-okx version.use_server_time=True means using the time in server,else using client local time,there are maybe different.
