### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'proxy'

### ISSUE THREAD

**Issue by luorock** [okxapi/python-okx#63]
import okx.Funding as Funding

flag = "1"  # live trading: 0, demo trading: 1

fundingAPI = Funding.FundingAPI(api_key, secret_key, passphrase, False, flag,proxy=None)

result = fundingAPI.get_currencies()
print(result)

run this get an error,

TypeError: Client.__init__() got an unexpected keyword argument 'proxy'

**Comment by okxapi** [comment]
update your python lib httpx version to the latest version

**Comment by Rain1047** [comment]
same problem, thanks for answering
