### ISSUE TITLE
Timestamp request expired with input param useServerTime=True

### ISSUE THREAD

**Issue by sixDollars** [okxapi/python-okx#64]
Try to open the private WS connection with 'useServerTime=True' for trading, but got error response. 
{"event":"error","msg":"Timestamp request expired","code":"60006","connId":"589e9aec"}
No such error observed if open the private WS connection with 'useServerTime=False'.  What gets wrong here? Is there a way to sync the time with okx server and how? 
Thanks

tradeDataWS = WsPrivateAsync(apiKey=API_KEY, passphrase=API_PASSPHRASE, secretKey=API_KEY_SECRET, url=tradeUrl, useServerTime=True)

**Comment by okxapi** [comment]
Parameter useServerTime is discarded in the latest version, please update.
