### ISSUE TITLE
class Client, API_URL might be a typo

### ISSUE THREAD

**Issue by coro-afk** [okxapi/python-okx#65]
class Client(object):
    API_URL = 'https://www.okex.com'

The URL should be 'https://www.okx.com'

**Comment by jerryoung** [comment]
感觉测试都没有测试的。

**Comment by jerryoung** [comment]
只能copy下来本地修改了？

**Comment by okxapi** [comment]
你们使用的是老版本吧，这个问题在之前版本就已经更新了。

**Comment by jerryoung** [comment]
> 你们使用的是老版本吧，这个问题在之前版本就已经更新了。

pip3 install python-okx，安装的最新版本呢。

**Comment by okxapi** [comment]
你可以看下github code里面 consts.py 中 API_URL的值，然后对比本地的代码

**Comment by jerryoung** [comment]
> 你可以看下github code里面 consts.py 中 API_URL的值，然后对比本地的代码

最新版本能发布下到pypi.org，上面不？

**Comment by okxapi** [comment]
发布了的呀 0.3.0

**Comment by okxapi** [comment]
只有老版本才有 class Client， 新版本 改名okxClient了

**Comment by jerryoung** [comment]
> 只有老版本才有 class Client， 新版本 改名okxClient，继承了httpx中的client类，这样拥有proxy代理能力了

我本地删除okx等sdk，重新拉去终于好了，估计和老版本冲突了，谢谢了。
