### ISSUE TITLE
获取的历史数据有偏差

### ISSUE THREAD

**Issue by zbx-122** [okxapi/python-okx#67]
获取的历史数据有偏差
运行以下代码
import okx.MarketData as MarketData
from datetime import datetime
market_api = MarketData.MarketAPI(flag='0')
result = market_api.get_index_candlesticks (
instId="BTC-USDT",
bar="4H",
limit=5
)
print(result)
得到结果
header:  {'Content-Type': 'application/json', 'x-simulated-trading': '0'}
domain: https://www.okx.com
url: /api/v5/market/index-candles?instId=BTC-USDT&bar=4H&limit=5
{'code': '0', 'msg': '', 'data': [['1723939200000', '59495.1', '60255.5', '59392.8', '59531.1', '0'], ['1723924800000', '59474.2', '59500.2', '59154.8', '59495.1', '1'], ['1723910400000', '59390', '59707.8', '59301.6', '59474.2', '1'], ['1723896000000', '59136', '59653.9', '59099.5', '59390', '1'], ['1723881600000', '59250.8', '59475.4', '59058.9', '59136', '1']]}
在官网上选择BTC/USDT现货得到的数据1723939200000/2024-08-18 08:00:00的开盘价为59499.8而不是59495.1（模拟盘也是59499.8），经过验证，所有价格都有问题
修改flag的值不会使结果变化，并且flag可以为任意值
如果是我获取BTC/USDT现货数据的代码哪里有问题，请帮我指出。如果能复现，那可能是交易所的问题，如果不能复现，那可能是我的环境的问题
还有一个问题，这些有偏差的价格从哪来的

**Comment by zbx-122** [comment]
虽然我还是不明白但是这个可以跑，此贴终结
import okx.MarketData as MarketData
flag = "0"  # 实盘:0 , 模拟盘：1

marketDataAPI =  MarketData.MarketAPI(flag=flag)

# 获取交易产品历史K线数据
result = marketDataAPI.get_history_candlesticks(
    instId="BTC-USDT",
    bar="4H",
    limit=5
)
print(result)

**Comment by Ilcosmoaaa** [comment]
你好哥，不知道你还做不做量化，我刚入门也是发现这个问题，不止okx，binance也是这样的，应该是一个什么常识。但是我还不知道，如果你知道了又看到了此评论，我十分期待你的回复。
