### ISSUE TITLE
How to close ur debug log?

### ISSUE THREAD

**Issue by Shaun-Yao** [okxapi/python-okx#73]
logging.getLogger("python-okx").setLevel(logging.WARNING) , logging.getLogger("okx").setLevel(logging.WARNING)  is not working.

**Comment by BennyThink** [comment]
```
logging.getLogger("httpx").setLevel(logging.WARNING)
```

**Comment by Shaun-Yao** [comment]
> ```python
> logging.getLogger("httpx").setLevel(logging.WARNING)
> ```

Thanks reply. It still doesn't work.  Maybe it's because it used a third-party library 'loguru'.

**Comment by Shaun-Yao** [comment]
> ```python
> logging.getLogger("httpx").setLevel(logging.WARNING)
> ```
Even if I switch to an v0.3.1 without 'loguru',  it still doesn't work when setting logging.getLogger("httpx").setLevel(logging.WARNING)

**Comment by okxapi** [comment]
You may use the `debug` parameter in Function API 
e.g. 
marketDataAPI =  MarketData.MarketAPI(debug = False)
