### ISSUE TITLE
Incorrect Values Returned by get_history_candlesticks and Missing confirm Parameter Support

### ISSUE THREAD

**Issue by csteri** [okxapi/python-okx#79]
1. The `get_history_candlesticks` function does not return the correct values. I have attached an image to illustrate this issue.
This is the link I am accessing both from Python and from the browser:
https://www.okx.com/api/v5/market/history-candles?instId=BTC-USDT-SWAP&before=1704060000000&bar=1Dutc&limit=100

![error](https://github.com/user-attachments/assets/24d1051d-422c-408a-9e4f-48d6fc7b7247)

3. Additionally, in the documentation [here](https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-candlesticks-history), it is specified that the `get_history_candlesticks` function accepts the `confirm` parameter with values `0 and 1`, but in the Python library, this parameter is not supported.
![missing](https://github.com/user-attachments/assets/23dd3ec8-9f67-4b68-8421-5fedeb36a2e6)

**Comment by okxapi** [comment]
1. You need to check the environment you access by Python is production.
2. `confirm` is a reponse parameter , not a request parameter
