### ISSUE TITLE
OKX Error code 60032

### ISSUE THREAD

**Issue by Anggel7x** [okxapi/python-okx#81]
* Operating system: Mac Pro Sequoia 15.0.1
  * Python Version: 3.10
  

I was trying to run the market making example for the page but I always receive the message of **API doesn't exist** to all my request. I am debugging using the wrapper on python and plain API web socket connections and still got the error. On a similar thread I found that for the Rest API the correct url to make the request was **https://my.okx.com** and not **https://www.okx.com** . Now I am trying to connect to the private demo web socket and sill have the same issue. My API key is well built since I was able to get the account information from a rest request without problem. I cannot help but wonder if those urls for WSS are outdated?? 

I am using this part of the documentation [production-trading-services](https://www.okx.com/docs-v5/en/#overview-production-trading-services) along with this article they made last year updating their urls [changes-to-v5-api-websocket](https://www.okx.com/help/changes-to-v5-api-websocket-subscription-parameter-and-url) plus this [websocket-login](https://www.okx.com/docs-v5/en/?shell#overview-websocket-login) example to test it out.

This is my code to test the connection on python:

```
import websocket
import hmac
import hashlib
import base64
import time
import json

# Define constants
url = "wss://wspap.okx.com:8443/ws/v5/business?brokerId=9999" #Defined in the documentation 
api_key = API_KEY
passphrase = API_PASSPHRASE
secret_key = API_KEY_SECRET 

# Generate the timestamp (in seconds)
timestamp = str(int(time.time()))

# Create the message to sign
method = "GET"
request_path = "/users/self/verify"
message = f"{timestamp}{method}{request_path}"

# Generate the HMAC SHA256 signature
signature = hmac.new(
    key=secret_key.encode('utf-8'),  # Secret key as bytes
    msg=message.encode('utf-8'),    # Concatenated string as bytes
    digestmod=hashlib.sha256        # Use SHA256
).digest()

# Perform Base64 encoding on the signature
base64_signature = base64.b64encode(signature).decode('utf-8')

# Prepare the login request payload
login_payload = {
    "op": "login",
    "args": [
        {
            "apiKey": api_key,
            "passphrase": passphrase,
            "timestamp": timestamp,
            "sign": base64_signature
        }
    ]
}

# Callback functions for WebSocket
def on_message(ws, message):
    print("Received message:", message)

def on_error(ws, error):
    print("Error occurred:", error)

def on_close(ws, close_status_code, close_msg):
    print("Connection closed:", close_status_code, close_msg)

def on_open(ws):
    print("Connection opened.")
    # Send the login payload
    ws.send(json.dumps(login_payload))

# Add the `x-simulated-trading` header required for demo connections
headers = {
    "x-simulated-trading": "1"
} 

# Create a WebSocketApp instance with headers
ws = websocket.WebSocketApp(
    url,
    header=headers,
    on_message=on_message,
    on_error=on_error,
    on_close=on_close
)

# Assign the on_open function
ws.on_open = on_open

# Run the WebSocket
ws.run_forever()
```

This is the message I got:

```
Connection opened.
Received message: {"event":"error","msg":"API key doesn't exist","code":"60032","connId":"e565de42"}
```

**Comment by okxapi** [comment]
Got the issue as follows. 
AttributeError: module 'websocket' has no attribute 'WebSocketApp'


----
If you want to use standard lib , may refer to : https://github.com/jane-cloud/Open-API-SDK-V5/blob/main/okx-python-sdk-api-v5/websocket_example.py

If you want to use wrapped lib, may refer to : https://github.com/okxapi/python-okx/blob/master/test/WsPrivateAsyncTest.py
> From: "Angel ***@***.***>
> Date:  Thu, Dec 5, 2024, 18:21
> Subject:  [okxapi/python-okx] OKX Error code 60032 (Issue #81)
> To: ***@***.***>
> Cc: ***@***.***>
> • Operating system: Mac Pro Sequoia 15.0.1
> • Python Version: 3.10
> I was trying to run the market making example for the page but I always receive the message of API doesn't exist to all my request. I am debugging using the wrapper on python and plain API web socket connections and still got the error. On a similar thread I found that for the Rest API the correct url to make the request was https://my.okx.com and not https://www.okx.com . Now I am trying to connect to the private demo web socket and sill have the same issue. My API key is well built since I was able to get the account information from a rest request without problem. I cannot help but wonder if those urls for WSS are outdated??
> I am using this part of the documentation production-trading-services<https://www.okx.com/docs-v5/en/#overview-production-trading-services> along with this article they made last year updating their urls changes-to-v5-api-websocket<https://www.okx.com/help/changes-to-v5-api-websocket-subscription-parameter-and-url> plus this websocket-login<https://www.okx.com/docs-v5/en/?shell#overview-websocket-login> example to test it out.
> This is my code to test the connection on python:import websocket
import hmac
import hashlib
import base64
import time
import json

# Define constants
url = "wss://wspap.okx.com:8443/ws/v5/business?brokerId=9999" #Defined in the documentation 
api_key = API_KEY
passphrase = API_PASSPHRASE
secret_key = API_KEY_SECRET 

# Generate the timestamp (in seconds)
timestamp = str(int(time.time()))

# Create the message to sign
method = "GET"
request_path = "/users/self/verify"
message = f"{timestamp}{method}{request_path}"

# Generate the HMAC SHA256 signature
signature = hmac.new(
    key=secret_key.encode('utf-8'),  # Secret key as bytes
    msg=message.encode('utf-8'),    # Concatenated string as bytes
    digestmod=hashlib.sha256        # Use SHA256
).digest()

# Perform Base64 encoding on the signature
base64_signature = base64.b64encode(signature).decode('utf-8')

# Prepare the login request payload
login_payload = {
    "op": "login",
    "args": [
        {
            "apiKey": api_key,
            "passphrase": passphrase,
            "timestamp": timestamp,
            "sign": base64_signature
        }
    ]
}

# Callback functions for WebSocket
def on_message(ws, message):
    print("Received message:", message)

def on_error(ws, error):
    print("Error occurred:", error)

def on_close(ws, close_status_code, close_msg):
    print("Connection closed:", close_status_code, close_msg)

def on_open(ws):
    print("Connection opened.")
    # Send the login payload
    ws.send(json.dumps(login_payload))

# Add the `x-simulated-trading` header required for demo connections
headers = {
    "x-simulated-trading": "1"
} 

# Create a WebSocketApp instance with headers
ws = websocket.WebSocketApp(
    url,
    header=headers,
    on_message=on_message,
    on_error=on_error,
    on_close=on_close
)

# Assign the on_open function
ws.on_open = on_open

# Run the WebSocket
ws.run_forever()
This is the message I got:Connection opened.
Received message: {"event":"error","msg":"API key doesn't exist","code":"60032","connId":"e565de42"}
