### ISSUE TITLE
Help, I want to use "close_limit". But not found this api

### ISSUE THREAD

**Issue by Joycessh** [okxapi/python-okx#85]
请问一下，如何使用限价平仓，我没有找到相关的方法

**Comment by okxapi** [comment]
只有按照市价平仓的接口。如果要使用限价平仓，可是使用下单接口 tradeAPI.place_order 方法。
比如long/short 模式下，平多头的仓位，可以指定参数 side=sell，ordType=limit，px传入你需要的限价

**Comment by Joycessh** [comment]
非常感谢，已经成功了。
